"""add_question_setter_fields_to_evaluator_assignment

Revision ID: 198dab01253c
Revises: 8df51e223e14
Create Date: 2025-12-27 12:15:34.666572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198dab01253c'
down_revision = '8df51e223e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_paper_evaluator_assignment', sa.Column('question_setter_id', sa.Integer(), nullable=True))
    op.add_column('exam_paper_evaluator_assignment', sa.Column('is_same_person', sa.Boolean(), nullable=True, server_default='0'))
    op.create_foreign_key('fk_exam_paper_evaluator_assignment_question_setter', 'exam_paper_evaluator_assignment', 'teacher', ['question_setter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_exam_paper_evaluator_assignment_question_setter', 'exam_paper_evaluator_assignment', type_='foreignkey')
    op.drop_column('exam_paper_evaluator_assignment', 'is_same_person')
    op.drop_column('exam_paper_evaluator_assignment', 'question_setter_id')
    # ### end Alembic commands ###
